import Head from 'next/head';
import { withLayout } from '../layouts/Layout';

function Home(): JSX.Element {
	return (
		<>
			<Head>
				<title>FirstShop</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
				<link rel='preconnect' href='https://fonts.googleapis.com' />
				<link rel='preconnect' href='https://fonts.gstatic.com' />
				<link
					rel='stylesheet'
					href='https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&display=swap'
				/>
			</Head>
			<h1>Index page</h1>
		</>
	);
}
