import Head from 'next/head';
import { GetStaticProps } from 'next';
import { ProductsModel } from '../interfaces/product.interface';
import axios from 'axios';
import { ProductCard } from '../components';
import { withLayout } from '../layouts/Layout';

function Home({ products }: HomeProps): JSX.Element {
	return (
		<>
			<Head>
				<title>FirstShop</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
				<link rel='preconnect' href='https://fonts.googleapis.com' />
				<link rel='preconnect' href='https://fonts.gstatic.com' />
				<link
					rel='stylesheet'
					href='https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&display=swap'
				/>
			</Head>
			{products &&
				products.map((product) => (
					<ProductCard
						key={product.id}
						title={product.title}
						price={product.price}
						description={product.description}
						image={product.image}
						category={product.category}
					/>
				))}
		</>
	);
}
export default withLayout(Home);
export const getStaticProps: GetStaticProps = async () => {
	const { data: products } = await axios.get<ProductsModel[]>(
		'https://fakestoreapi.com/products'
	);
	return {
		props: {
			products,
		},
	};
};

interface HomeProps extends Record<string, unknown> {
	products: ProductsModel[];
}
