import axios from 'axios';
import {GetServerSideProps} from 'next';
import Head from 'next/head';
import { AllProducts, ProductCard } from '../components';
import { ProductsModel } from '../interfaces/product.interface';
import { withLayout } from '../layouts/Layout';

function Home({ products }: ProductProps): JSX.Element {
	return (
		<>
			<Head>
				<title>FirstShop</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
				<link rel='preconnect' href='https://fonts.googleapis.com' />
				<link rel='preconnect' href='https://fonts.gstatic.com' />
			</Head>
			<AllProducts products={products} />
		</>
	);
}
export default withLayout(Home);
export const getServerSideProps: GetServerSideProps = async () => {
	const { data: products } = await axios.get<ProductsModel[]>(
		'https://fakestoreapi.com/products'
	);
	return {
		props: {
			products,
		},
	};
};

interface ProductProps extends Record<string, unknown> {
	products: ProductsModel[];
}
